"""
Result writer: serialize the output of a single operation to headerless CSV.

Mirrors the loader's PyArrow-based, headerless-numeric convention so anything written
here can be fed straight back into the loader. A result may be:

* a single array / scalar  -> written verbatim to the requested path;
* a mapping ``name -> array`` (e.g. ``{"L": ..., "U": ...}`` from a factorization) ->
  written as one file per component, named ``<stem>.<name><suffix>``, so each CSV stays
  a clean, round-trippable matrix.
"""
from pathlib import Path
import numpy as np
import pyarrow as pa
import pyarrow.csv as pv

_WRITE_OPTS = pv.WriteOptions(include_header=False)


def _to_table(value) -> pa.Table:
    """Coerce a scalar / 1D / 2D value into a 2D PyArrow table with autogenerated columns.

    PyArrow has no complex type: arrays whose imaginary part is negligible are collapsed
    to their real part, otherwise the real part is kept (the imaginary part is reported on
    stdout by the CLI, not the CSV).
    """
    arr = np.atleast_2d(np.asarray(value))
    if np.iscomplexobj(arr):
        arr = np.asarray(np.real_if_close(arr, tol=1000))
        if np.iscomplexobj(arr):
            arr = arr.real
    return pa.table({f"f{i}": arr[:, i] for i in range(arr.shape[1])})


def write_csv(result, path) -> list[Path]:
    """Write `result` to `path` (one file per named component) and return the paths written."""
    path = Path(path)

    if isinstance(result, dict):
        if len(result) == 1:
            (value,) = result.values()
            pv.write_csv(_to_table(value), path, write_options=_WRITE_OPTS)
            return [path]
        written = []
        suffix = path.suffix or ".csv"
        for name, value in result.items():
            component = path.with_name(f"{path.stem}.{name}{suffix}")
            pv.write_csv(_to_table(value), component, write_options=_WRITE_OPTS)
            written.append(component)
        return written

    pv.write_csv(_to_table(result), path, write_options=_WRITE_OPTS)
    return [path]
